### ISSUE TITLE
Where is the mae_env.yml ?

### ISSUE THREAD

**Issue by unoct** [facebookresearch/AudioMAE#10]
Hi, I couldn't find it, Maybe I get something wrong?
Thank you !!

**Comment by berniebear** [comment]
Hello,
please find the updated the env [here](https://github.com/facebookresearch/AudioMAE/blob/main/mae_env.yml). You may also untar then source the packed conda env [here](https://drive.google.com/file/d/1ECVmVyscVqmhI7OQa0nghIsWVaZhZx3q/view?usp=sharing). Thank you.
