### ISSUE TITLE
Could u release self-supervised weights without fine-tuning?

### ISSUE THREAD

**Issue by haidog-yaqub** [facebookresearch/AudioMAE#11]
I wish to fine-tune pre-trained model on a downstream sound similarity task, I wish to apply self-supervied model without the influence of annotation. 
Could u release the self-supervised weights without fine-tuning on audioset?

**Comment by berniebear** [comment]
Hello, thank you for your interest in our work. As described in [4](https://drive.google.com/file/d/1rRsmU8x7D-x4BvcPyroUJwU18eixNfKg/view?usp=sharing), the AudioSet self-supervised pretrained model (pretrained.pth) can be found [here](https://drive.google.com/file/d/1rRsmU8x7D-x4BvcPyroUJwU18eixNfKg/view?usp=sharing). Thank you.
