### ISSUE TITLE
Can't download any ckpt files in github

### ISSUE THREAD

**Issue by joo-young-lee** [facebookresearch/AudioMAE#17]
Can't download any ckpt files in github.

**Comment by berniebear** [comment]
Hello, thank you for the reminder! Somehow the original urls are broken. We have updated the urls README.md to fix the issue. Please find the updated ckpts as bellow:
1. ViT-B, AS-2M [pretrained](https://drive.google.com/file/d/1ni_DV4dRf7GxM8k-Eirx71WP9Gg89wwu/view?usp=share_link)
2. ViT-B, AS-2M pretrained+[finetuned](https://drive.google.com/file/d/18EsFOyZYvBYHkJ7_n7JFFWbj6crz01gq/view?usp=share_link)
