### ISSUE TITLE
where is the weight_train.csv?

### ISSUE THREAD

**Issue by LinB203** [facebookresearch/AudioMAE#9]
Hi, thank you for your wonderful work. I'm confuse about where is the weight_train.csv? and weight_train_all.csv?

**Comment by berniebear** [comment]
Hello,
Thank you for your interest in our work. I guess you mean the weight csv file for balanced fine-tuning on the unbalanced AudioSet-2M? In that case please find the weight_train_all.csv [here](https://drive.google.com/file/d/1EF7ubs6FJQL1fQVF8Ki6RsHxQL-5-YCI/view?usp=sharing) or in the updated data json [link](https://drive.google.com/file/d/1nr1zs7uhL0By-yI9UPMMXCORK0PeUMYi/view?usp=share_link). For custom unbalanced datasets, you may also use [gen_weight.py](https://github.com/facebookresearch/AudioMAE/blob/main/dataset/audioset/gen_weight.py) to generate weight file. Thank you.
